lgvd_config:
  num_steps: 200
  lr: 1e-5
  tau: 0.01
  lr_min_ratio: 0.01


operator:
  name: inpainting
  mask_type: random
  mask_prob_range: [0.50, 0.51]  # for random
  resolution: 64
  sigma: 0.05
